apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blue-green
spec:
  ingressClassName: nginx
  rules:
    - host: "hello-world.info"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: green
                port:
                  number: 80
